apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
        env: prod

  template:
    metadata:
     name: dev-pod
     labels:
       env: prod
    spec:
     containers:
      - name: dev-con
        image: vkk1310/web:latest
